[server]
address = "127.0.0.1"
port = 8501
headless = true
maxUploadSize = 10
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#087F8C"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#EDF2F7"
textColor = "#162B3A"
font = "sans serif"
